
substitutions:
# Уникальное имя этой конфигурации, стоит использовать только латинские буквы и цифры, никаких пробелов или
# спецсимволов, например, "tclac". Если будет несколько модулей кондиционера, то device_name надо изменить,
# например, добавляя цифры: tclac1, tclac2, tclac3...
  device_name: kuboac1
# Человеческое имя для кондиционера, для интерфейса:
  humanly_name: Kubo Air Conditioning 12K BTU
# Настройки подключения к WiFI, данные могут храниться в файле "secret" в ESPHome, если нет- редактируем:
# Имя точки доступа WiFI:
  wifi_ssid: !secret wifi_ssid
# Пароль точки доступа WiFI:
  wifi_password: !secret wifi_password
# Пароль для точки доступа для восстановления, имя точки доступа будет: "{device_name} Fallback Hotspot"
  recovery_pass: mKSzmBdt7DAj
# Пароль для обновления по воздуху, генерируется один раз и потом используется всегда на автомате:
  ota_pass: 90cf525a594c8bb2cbf917bc2c2fa058
# Ключ подключения к Home Assistant API, новый ключ можно получить здесь: https://esphome.io/components/api.html:
  api_key: lmUoWsWs1oqSfJqLFsA6PisHSx4Y1G+iu7V3PDIqpXk=
# Выводы модуля, к которым подключен UART:
  uart_rx: GPIO13
  uart_tx: GPIO15
# Выводы модуля для подключения сигнальных светодиодов, для работы надо раскомментировать "leds" в packages
# иначе работать не будет совсем и можно писать сюда вообще что угодною. Для тех, кто просил их удалить.
  receive_led: GPIO6
  transmit_led: GPIO4

packages:
  remote_package:
    url: https://github.com/I-am-nightingale/tclac.git
    ref: master
    files:
      - packages/core.yaml # Ядро всего сущего
      # Подключение дополнительных опций:
      # - packages/leds.yaml
    refresh: 30s

# Выбранный модуль, прошиваемой этой прошивкой. Можно раскомментировать готовую заготовку, удалив имеющуюся:

# ESP-01S
esp8266:
  board: esp01_1m

web_server:
  port: 80


# Светодиод статуса. Включать по желанию при наличии свободных пинов
#status_led:
#  pin:
#    number: GPIO5
#    inverted: false